apiVersion: apps/v1
kind: Deployment
metadata:
  name: mygo-deployment
  labels:
    app: mygo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: mygo
  template:
    metadata:
      labels:
        app: mygo
    spec:
      containers:
        - name: mygo
          image: mygo:v3
          imagePullPolicy: IfNotPresent # 优先用本地，如果本地没有再去下载
          command: ["/myGo"] # 如果存在，在启动镜像时会覆盖dockerfile中的cmd
          args: ["-c", "/etc/config/mygo.toml"]
          ports:
            - containerPort: 8090
              name: mygo-web
          volumeMounts:
            - name: mygo-conf-volume
              mountPath: /etc/config
      volumes:
        - name: mygo-conf-volume
          configMap:
            name: mygo-conf
            items:
            - key: mygo-conf
              path: mygo.toml