#环境
env = "testing"

app_name = "my_go"

http_port = ":8081"

[mysql]
    [mysql.master]
    user = "root"
    password = ""
    host = "192.168.50.196" # docker访问本地机
    port = 3306
    db = "test"
    max_idle = 100
    max_open = 200
    name = ""
    debug = true