name: ci

on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
    tags:
      - v*
    branches:
      - master

jobs:
  go-mod:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check go mod
        run: |
          go mod download
          git diff --exit-code go.mod

  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: latest
          # skip cache because of flaky behaviors
          skip-build-cache: true
          skip-pkg-cache: true

#   build:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Build
#       run: go build -v ./...

#     - name: Test
#       run: go test -v ./...
